// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJab-R0TujmDvfDjGt9opATQ6_H4aNlQ',
    appId: '1:922312700544:web:6a6c74dff0b946a2186c65',
    messagingSenderId: '922312700544',
    projectId: 'chat-app-60238',
    authDomain: 'chat-app-60238.firebaseapp.com',
    storageBucket: 'chat-app-60238.firebasestorage.app',
    measurementId: 'G-NPXJHN3R48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJoRj8BUgV6WGljfBzlv8WPxupFCgqQj0',
    appId: '1:922312700544:android:6e7bdb0c408d8ea8186c65',
    messagingSenderId: '922312700544',
    projectId: 'chat-app-60238',
    storageBucket: 'chat-app-60238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZU9rxSzTA_wVqxNzpZsrUAYd8VQ7kHs',
    appId: '1:922312700544:ios:280e223a116ac78c186c65',
    messagingSenderId: '922312700544',
    projectId: 'chat-app-60238',
    storageBucket: 'chat-app-60238.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZU9rxSzTA_wVqxNzpZsrUAYd8VQ7kHs',
    appId: '1:922312700544:ios:280e223a116ac78c186c65',
    messagingSenderId: '922312700544',
    projectId: 'chat-app-60238',
    storageBucket: 'chat-app-60238.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeJab-R0TujmDvfDjGt9opATQ6_H4aNlQ',
    appId: '1:922312700544:web:b72a4f2fd8a22fba186c65',
    messagingSenderId: '922312700544',
    projectId: 'chat-app-60238',
    authDomain: 'chat-app-60238.firebaseapp.com',
    storageBucket: 'chat-app-60238.firebasestorage.app',
    measurementId: 'G-HC2384GZ9G',
  );
}
